export type Chain =
  | "Arbitrum"
  | "Avalanche"
  | "Base"
  | "Bitcoin"
  | "BitcoinCash"
  | "Blast"
  | "BSC"
  | "CronosChain"
  | "Dash"
  | "Dogecoin"
  | "Dydx"
  | "Ethereum"
  | "Cosmos"
  | "Kujira"
  | "Litecoin"
  | "MayaChain"
  | "Noble"
  | "Optimism"
  | "Osmosis"
  | "Polkadot"
  | "Polygon"
  | "Solana"
  | "Sui"
  | "Terra"
  | "TerraClassic"
  | "THORChain"
  | "TON"
  | "Tron"
  | "XRP"
  | "Zksync";

export const defaultChain: Chain = "Ethereum";
