// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,json_types=true"
// @generated from file thorchain.proto (package types, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thorchain.proto.
 */
export const file_thorchain: GenFile = /*@__PURE__*/
  fileDesc("Cg90aG9yY2hhaW4ucHJvdG8SBXR5cGVzImUKBUFzc2V0Eg0KBWNoYWluGAEgASgJEg4KBnN5bWJvbBgCIAEoCRIOCgZ0aWNrZXIYAyABKAkSDQoFc3ludGgYBCABKAgSDQoFdHJhZGUYBSABKAgSDwoHc2VjdXJlZBgGIAEoCCJFCgRDb2luEhsKBWFzc2V0GAEgASgLMgwudHlwZXMuQXNzZXQSDgoGYW1vdW50GAIgASgJEhAKCGRlY2ltYWxzGAMgASgDIkYKCk1zZ0RlcG9zaXQSGgoFY29pbnMYASADKAsyCy50eXBlcy5Db2luEgwKBG1lbW8YAiABKAkSDgoGc2lnbmVyGAMgASgMQiNaIWdpdGh1Yi5jb20vdnVsdGlzaWcvcmVjaXBlcy90eXBlc2IGcHJvdG8z");

/**
 * Asset represents a THORChain asset identifier
 *
 * @generated from message types.Asset
 */
export type Asset = Message<"types.Asset"> & {
  /**
   * @generated from field: string chain = 1;
   */
  chain: string;

  /**
   * @generated from field: string symbol = 2;
   */
  symbol: string;

  /**
   * @generated from field: string ticker = 3;
   */
  ticker: string;

  /**
   * @generated from field: bool synth = 4;
   */
  synth: boolean;

  /**
   * @generated from field: bool trade = 5;
   */
  trade: boolean;

  /**
   * @generated from field: bool secured = 6;
   */
  secured: boolean;
};

/**
 * Asset represents a THORChain asset identifier
 *
 * @generated from message types.Asset
 */
export type AssetJson = {
  /**
   * @generated from field: string chain = 1;
   */
  chain?: string;

  /**
   * @generated from field: string symbol = 2;
   */
  symbol?: string;

  /**
   * @generated from field: string ticker = 3;
   */
  ticker?: string;

  /**
   * @generated from field: bool synth = 4;
   */
  synth?: boolean;

  /**
   * @generated from field: bool trade = 5;
   */
  trade?: boolean;

  /**
   * @generated from field: bool secured = 6;
   */
  secured?: boolean;
};

/**
 * Describes the message types.Asset.
 * Use `create(AssetSchema)` to create a new message.
 */
export const AssetSchema: GenMessage<Asset, {jsonType: AssetJson}> = /*@__PURE__*/
  messageDesc(file_thorchain, 0);

/**
 * Coin represents a token with denomination and amount (matching common.Coin)
 *
 * @generated from message types.Coin
 */
export type Coin = Message<"types.Coin"> & {
  /**
   * @generated from field: types.Asset asset = 1;
   */
  asset?: Asset;

  /**
   * @generated from field: string amount = 2;
   */
  amount: string;

  /**
   * @generated from field: int64 decimals = 3;
   */
  decimals: bigint;
};

/**
 * Coin represents a token with denomination and amount (matching common.Coin)
 *
 * @generated from message types.Coin
 */
export type CoinJson = {
  /**
   * @generated from field: types.Asset asset = 1;
   */
  asset?: AssetJson;

  /**
   * @generated from field: string amount = 2;
   */
  amount?: string;

  /**
   * @generated from field: int64 decimals = 3;
   */
  decimals?: string;
};

/**
 * Describes the message types.Coin.
 * Use `create(CoinSchema)` to create a new message.
 */
export const CoinSchema: GenMessage<Coin, {jsonType: CoinJson}> = /*@__PURE__*/
  messageDesc(file_thorchain, 1);

/**
 * MsgDeposit represents THORChain's MsgDeposit message for swaps/deposits
 *
 * @generated from message types.MsgDeposit
 */
export type MsgDeposit = Message<"types.MsgDeposit"> & {
  /**
   * Coins being deposited
   *
   * @generated from field: repeated types.Coin coins = 1;
   */
  coins: Coin[];

  /**
   * Memo contains swap instructions including destination address
   *
   * @generated from field: string memo = 2;
   */
  memo: string;

  /**
   * Signer is the address of the depositor (as bytes for bech32 compatibility)
   *
   * @generated from field: bytes signer = 3;
   */
  signer: Uint8Array;
};

/**
 * MsgDeposit represents THORChain's MsgDeposit message for swaps/deposits
 *
 * @generated from message types.MsgDeposit
 */
export type MsgDepositJson = {
  /**
   * Coins being deposited
   *
   * @generated from field: repeated types.Coin coins = 1;
   */
  coins?: CoinJson[];

  /**
   * Memo contains swap instructions including destination address
   *
   * @generated from field: string memo = 2;
   */
  memo?: string;

  /**
   * Signer is the address of the depositor (as bytes for bech32 compatibility)
   *
   * @generated from field: bytes signer = 3;
   */
  signer?: string;
};

/**
 * Describes the message types.MsgDeposit.
 * Use `create(MsgDepositSchema)` to create a new message.
 */
export const MsgDepositSchema: GenMessage<MsgDeposit, {jsonType: MsgDepositJson}> = /*@__PURE__*/
  messageDesc(file_thorchain, 2);

